version: '3.4'
services:
  mysql:
    image: mysql
    container_name: my-password-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      MYSQL_DATABASE: my-password
      MYSQL_ROOT_PASSWORD: "Q4BJm9lwPlWGZUkn9uCc"
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
    restart: always
    networks:
      - my-password

  my-password:
    build: .
    container_name: my-password
    restart: always
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    #Config ip for container, you can remove if It's not necessary
    networks:
      my-password:
        ipv4_address: 172.30.0.3

networks:
  my-password:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16