version: '3.4'
services:
  mysql:
    image: mysql
    container_name: my-password-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    environment:
      MYSQL_DATABASE: my-password
      MYSQL_ROOT_PASSWORD: "Q4BJm9lwPlWGZUkn9uCc"
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
    restart: always

  my-password:
    build: .
    container_name: my-password
    restart: always
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./logs:/app/logs
    ports:
      - 172.31.1.134:8080:8080
      # or use public port over public network
      #- 8080:8080
